### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by zygimantus** [TatuLund/grid-scroll-extension#1]
Does this plugin require that `GridScrollExtension ext1 = new GridScrollExtension(grid);` would be used only inside _init_ method or it could also be used inside _enter_ method of a **View** class? Because the mentioned _enter_ does not work.

**Comment by TatuLund** [comment]
GridScrollExtension ext1 = new GridScrollExtension(grid); can be also elsewhere, not just init.

**Comment by zygimantus** [comment]
And that's it? Nothing more is required?

**Comment by TatuLund** [comment]
Yes. Depending what you use it for, you can also use following API given by the extension.

public void restoreScrollPosition()

public int getLastXPosition()

public int getLastYPosition()

public void setScrollPosition(int Xposition, int Yposition)
