### ISSUE TITLE
Dragging the right edge of the last column doesn't make it occupy the remaining space

### ISSUE THREAD

**Issue by fgrilli** [TatuLund/grid-scroll-extension#10]
Apparently the compensation mode doesn't work when the last column is resized. 
For a moment, it looks like it stretches to occupy all the available space but then is back 
to the initial width.
Fired up superdev mode and tried to figure out why but could not pinpoint the cause of the problem.

**Comment by TatuLund** [comment]
> Apparently the compensation mode doesn't work when the last column is resized.

Can you tell me which compensation mode you used, since there is two alternatives?

**Comment by fgrilli** [comment]
> Can you tell me which compensation mode you used, since there is two alternatives?

RESIZE_COLUMN

**Comment by TatuLund** [comment]
This was interesting case, there is some bug in Grid itself that causes this sort of issues, but I was able to workaround it. Notably that bug causes maximum width setting not to be obeyed. I had already partial workaround for that in add-on, but now it seems to work better. The workaround is not pretty though. Check version 2.3.5 from Directory.

**Comment by fgrilli** [comment]
> This was interesting case, there is some bug in Grid itself that causes this sort of issues, but I was able to workaround it.

Awesome, thanks a lot!
