### ISSUE TITLE
Possibility to get the absolute width of the entire grid

### ISSUE THREAD

**Issue by sirbris** [TatuLund/grid-scroll-extension#4]
Would it be possible to get access to the width of the whole grid in pixels through the extension? Would be helpful to overcome the issue of empty space next to the last column after resizing another column. The setAutoResizeWidth function is nice but does not work for grids which should stay full size

**Comment by TatuLund** [comment]
> Would it be possible to get access to the width of the whole grid in pixels through the extension?

At the moment you can already sum the widths of the columns, but then you would need to take into account possible scroll bar. But I think it would be rather straightforward to add such convenience method.

> The setAutoResizeWidth function is nice but does not work for grids which should stay full size

No, and that is not the intention either. If you want the grid to stay full size and let columns to re-autoadjust, you need to set the widths of the columns to undefined with Grid.getColumn(..).setWidthUndefined() method.

**Comment by sirbris** [comment]
That method would really help us, because summing up the column's width only works when the columns fit exactly in the grid... after resizing a column and then resizing the surrounding container (SplitPanel, Window, browser...) there's no way (without extra extension) to get the grid's width, or am I missing another possibility? We only want to programatically resize the last visible column to fit the entire grid, if there's an empty space after it.

**Comment by TatuLund** [comment]
This feature has been added to 2.2.0. There are some other new features and couple of bug fixes there too.
