### ISSUE TITLE
scrollTo() not working after initial creation

### ISSUE THREAD

**Issue by sirbris** [TatuLund/grid-scroll-extension#5]
When I create a new grid with the scroll extension and want to scroll to a specific item directly, the extension resets the scroll position to top. I get that the restoreScrollPosition needs to be called at a later point, but is there a workaround to call "scrollTo" AFTER the extension resets last positions?

**Comment by TatuLund** [comment]
Are you now referring to Grid,scrollTo() method, not the scrollTo method of the extension?

**Comment by sirbris** [comment]
Sorry, yes, the scrollTo(item) from Grid/TreeGrid... after everything is attached, rendered and so on, scrollTo(item) works but if I try to build & show the Grid directly with a selected item that needs scrolling, it won't work with the extension. Is there a way with a listener or should I override restoreScrollPosition or something like that?

**Comment by TatuLund** [comment]
I can confirm this. It requires some more thinking how to solve the issue.
