### ISSUE TITLE
2.2.1 disables vertical scrollbar and hides column hide/show icon

### ISSUE THREAD

**Issue by neerup** [TatuLund/grid-scroll-extension#6]
After upgrading from 2.2.0 to 2.2.1 my vertical scrollbars disapears, leaving me without any chance of scrolling the grid without a mousewheel, and my column hide/show icon is not visible.

![image](https://user-images.githubusercontent.com/4113036/42614676-338e5e14-85a7-11e8-8be0-bdd1fdfde5df.png)
![image](https://user-images.githubusercontent.com/4113036/42614702-499c46c6-85a7-11e8-9f0d-40cdbdd6cfcd.png)

**Comment by TatuLund** [comment]
Thanks for reporting this.

However I seem not be able to replicate the issue with demo app of the project with framework version 8.4.4. The scrollbar is not disappearing with it. So I need more information on this. Do you have sample project? Which browser was used in your testing? Which framework version was used? Did you remember recompile widgetset?
