### ISSUE TITLE
Fix typo in "ColumnResizeComponesationMode" setter and getter

### ISSUE THREAD

**Issue by fgrilli** [TatuLund/grid-scroll-extension#8]
There is a small typo in the setter and getter methods for `ColumnResizeComponesationMode`: `Componesetation` should clearly be `Compensation`.

**Comment by TatuLund** [comment]
Good finding, that is correct, I should fix that.

**Comment by TatuLund** [comment]
Version 2.3.4 has been now released in Directory

**Comment by fgrilli** [comment]
Thank you!
